trigger: none
pool:
  vmImage: 'windows-latest'

variables:
- group: azureterrafromauth


stages:
  # Stage 1: Initialization (init, validate, lint)
  - stage: Initialization
    jobs:
      - job: TerraformInit
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'shashi sub svc conn'
              backendAzureRmStorageAccountName: 'skinktfstateshashi'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: 'tfstate.state'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'validate'
  - stage: tfdeploy
    condition: succeeded('Initialization')
    dependsOn: Initialization
    jobs:
      - job: apply
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'shashi sub svc conn'
              scriptType: 'ps'
              scriptLocation: 'inlineScript'
              inlineScript: |
                $env:ARM_CLIENT_ID = ${ARM_CLIENT_ID}
                $env:ARM_CLIENT_SECRET =  ${ARM_CLIENT_SECRET}
                $env:ARM_TENANT_ID =  ${ARM_TENANT_ID}
                $env:ARM_SUBSCRIPTION_ID =  ${ARM_SUBSCRIPTION_ID}
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'shashi sub svc conn'
              backendAzureRmStorageAccountName: 'skinktfstateshashi'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: 'tfstate.state' 
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'shashi sub svc conn'