trigger: none
pool:
  vmImage: 'windows-latest'

variables:
- group: azureterrafromauth


stages:
  # Stage 1: Initialization (init, validate, lint)
  - stage: Initialization
    jobs:
      - job: TerraformInit
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'shashi sub svc conn'
              backendAzureRmStorageAccountName: 'skinktfstateshashi'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: 'tfstate.state'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'validate'
  - stage: tfdeploy
    condition: succeeded('Initialization')
    dependsOn: Initialization
    jobs:
      - job: apply
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'
          - script: |
              export ARM_CLIENT_ID=$(ARM_CLIENT_ID)
              export ARM_CLIENT_SECRET=$(ARM_CLIENT_SECRET)
              export ARM_SUBSCRIPTION_ID=$(ARM_SUBSCRIPTION_ID)
              export ARM_TENANT_ID=$(ARM_TENANT_ID)
            displayName: 'Set Azure Authentication Variables'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'shashi sub svc conn'
              backendAzureRmStorageAccountName: 'skinktfstateshashi'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: 'tfstate.state' 
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'shashi sub svc conn'